config/routes.rb
Rails.application.routes.draw do
  resources :sightings do
    get :get_sightings, on: :collection
  end

  resources :animals

  root 'animals#index'

end

app/models/animal.rb
class Animal < ActiveRecord::Base
  has_many :sightings
  validates :common_name, length: { minimum: 1 }
  validates :latin_name, length: { minimum: 1 }
  validates :kingdom, length: { minimum: 1 }
end

app/models/sighting.rb
class Sighting < ActiveRecord::Base
  belongs_to :animal
  validates :latitude, length: { minimum: 1 }
  validates :longitude, length: {minimum: 1}
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :set_animal, only: [:show, :edit, :update, :destroy]

  # GET /animals
  # GET /animals.json
  def index
    @animals = Animal.all
  end

  # GET /animals/1
  # GET /animals/1.json
  def show
  end

  # GET /animals/new
  def new
    @animal = Animal.new
  end

  # GET /animals/1/edit
  def edit
  end

  # POST /animals
  # POST /animals.json
  def create
    @animal = Animal.new(animal_params)

    respond_to do |format|
      if @animal.save
        format.html { redirect_to @animal, notice: 'Animal was successfully created.' }
        format.json { render :show, status: :created, location: @animal }
      else
        format.html { render :new }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /animals/1
  # PATCH/PUT /animals/1.json
  def update
    respond_to do |format|
      if @animal.update(animal_params)
        format.html { redirect_to @animal, notice: 'Animal was successfully updated.' }
        format.json { render :show, status: :ok, location: @animal }
      else
        format.html { render :edit }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /animals/1
  # DELETE /animals/1.json
  def destroy
    @animal.destroy
    respond_to do |format|
      format.html { redirect_to animals_url, notice: 'Animal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_animal
      @animal = Animal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def animal_params
      params.require(:animal).permit(:common_name, :latin_name, :kingdom)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sightings_controller.rb
class SightingsController < ApplicationController
  before_action :set_sighting, only: [:show, :edit, :update, :destroy]

  # GET /sightings
  # GET /sightings.json
  def index
    @sightings = Sighting.all
  end

  # GET /sightings/1
  # GET /sightings/1.json
  def show
  end

  # GET /sightings/new
  def new
    @sighting = Sighting.new
    @animals_for_select = Animal.all.map do |animal|
    [animal.common_name, animal.id]
    end

  end



  # GET /sightings/1/edit
  def edit
    @animals_for_select = Animal.all.map do |animal|
    [animal.common_name, animal.id]
    end
  end

  def get_sightings
    @sightings = Sighting.all
    sightings = []
    @sightings.each do |sighting|
      sightings << {
        id: sighting.id,
        title: sighting.animal.common_name,
        start: DateTime.new(sighting.date.year, sighting.date.month, sighting.date.day, sighting.time.hour, sighting.time.min, sighting.time.sec).to_s,
        url: Rails.application.routes.url_helpers.sighting_path(sighting.id)}
    end
    render :json => sightings.to_json
  end

  # POST /sightings
  # POST /sightings.json
  def create
    @sighting = Sighting.new(sighting_params)

    respond_to do |format|
      if @sighting.save
        format.html { redirect_to @sighting, notice: 'Sighting was successfully created.' }
        format.json { render :show, status: :created, location: @sighting }
      else
        format.html { render :new }
        format.json { render json: @sighting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sightings/1
  # PATCH/PUT /sightings/1.json
  def update
    respond_to do |format|
      if @sighting.update(sighting_params)
        format.html { redirect_to @sighting, notice: 'Sighting was successfully updated.' }
        format.json { render :show, status: :ok, location: @sighting }
      else
        format.html { render :edit }
        format.json { render json: @sighting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sightings/1
  # DELETE /sightings/1.json
  def destroy
    @sighting.destroy
    respond_to do |format|
      format.html { redirect_to sightings_url, notice: 'Sighting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def index
    if !(params[:start_date]).nil? && !(params[:end_date]).nil?
      if !(params[:start_date]).empty? && !(params[:end_date]).empty?
        @sightings = Sighting.where(date:   params[:start_date]..params[:end_date], region: params[:region])
        render('sightings/index.html.erb')
      else
        @sightings = Sighting.all
      end
    else
      @sightings = Sighting.all
      render('sightings/index.html.erb')
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sighting
      @sighting = Sighting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sighting_params
      params.require(:sighting).permit(:date, :time, :latitude, :longitude, :region, :animal_id)
    end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sightings_helper.rb
module SightingsHelper
end

app/views/animals/_form.html.erb
<%= form_for(@animal) do |f| %>
  <% if @animal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@animal.errors.count, "error") %> prohibited this animal from being saved:</h2>

      <ul>
      <% @animal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :common_name %><br>
    <%= f.text_field :common_name %>
  </div>
  <div class="field">
    <%= f.label :latin_name %><br>
    <%= f.text_field :latin_name %>
  </div>
  <div class="field">
    <%= f.label :kingdom %><br>
    <%= f.text_field :kingdom %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/animals/edit.html.erb
<h1>Editing Animal</h1>

<%= render 'form' %>

<%= link_to 'Show', @animal %> |
<%= link_to 'Back', animals_path %>

app/views/animals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Animals</h1>

<table class="table">
  <thead>
    <tr>
      <th>Common name</th>
      <th>Latin name</th>
      <th>Kingdom</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id="animalTable">
    <% @animals.each do |animal| %>
      <tr >
        <td><%= animal.common_name %></td>
        <td><%= animal.latin_name %></td>
        <td><%= animal.kingdom %></td>
        <td><%= link_to 'Show', animal %></td>
        <td><%= link_to 'Edit', edit_animal_path(animal) %></td>
        <td><%= link_to 'Destroy', animal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<a href='/sightings'>Sightings</a>

<%= link_to 'New Animal', new_animal_path %>

<p>
<input type="text" name="animal[common_name]" placeholder="Common Name" id="common_name">
<input type="text" name="animal[latin_name]" placeholder="Latin Name" id="latin_name">
<input type="text" name="animal[kingdom]" placeholder="Kingdom" id="kingdom">
<input type="button" value="submit" id="add_new_animal"></button>
</p>

app/views/animals/new.html.erb
<h1>New Animal</h1>

<%= render 'form' %>

<%= link_to 'Back', animals_path %>

app/views/animals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Common name:</strong>
  <%= @animal.common_name %>
</p>

<p>
  <strong>Latin name:</strong>
  <%= @animal.latin_name %>
</p>

<p>
  <strong>Kingdom:</strong>
  <%= @animal.kingdom %>
</p>

<p> <strong>Sightings:</strong>
  <ul id="sighting_list">
    <% @animal.sightings.each do |sighting| %>
        <li>Date:
          <%= sighting.date %>
          <br> Latitude:
          <%= sighting.latitude %>
          <br> Longitude:
          <%= sighting.longitude %>
          <br>Region:
          <%= sighting.region %>
        </li>
    <% end %>
  </ul>
</p>


<p>
<input type="date" name="sighting[date]" placeholder="Date" id="s_date">
<input type="time" name="sighting[time]" placeholder="Time" id="s_time">
<input type="float" name="sighting[latitude]" placeholder="Latitude" id="latitude">
<input type="float" name="sighting[longitude]" placeholder="Longitude" id="longitude">
<div class="field" name="sighting[region]" >
<%= select_tag("region", options_for_select([['north' ,'north'], ['south', 'south'], ['east', 'east'], ['west', 'west']])) %>
</div>
<input type="hidden" name="animal_id" id="animal_id" value="<%=@animal.id%>"/>
<input type="button" value="submit" id="add_new_sighting"></button>
</p>

<%= link_to 'Edit', edit_animal_path(@animal) %> |
<%= link_to 'Back', animals_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wildlifeapp</title>

<script src="https://code.jquery.com/jquery-3.1.0.min.js" integrity="sha256-cCueBR6CsyA4/9szpPfrX3s49M9vUU5BgtiJj06wt/s=" crossorigin="anonymous"></script>

  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sightings/_form.html.erb
<%= form_for(@sighting) do |f| %>
  <% if @sighting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sighting.errors.count, "error") %> prohibited this sighting from being saved:</h2>

      <ul>
      <% @sighting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.time_select :time %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
  <%= select(:sighting, :region, options_for_select([['north' ,'north'], ['south', 'south'], ['east', 'east'], ['west', 'west']])) %>
  </div>
  <div class="field">
    <%= select(:sighting, :animal_id, @animals_for_select) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sightings/edit.html.erb
<h1>Editing Sighting</h1>

<%= render 'form' %>

<%= link_to 'Show', @sighting %> |
<%= link_to 'Back', sightings_path %>

app/views/sightings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sightings</h1>

<table class="table">
  <thead>
    <tr>
      <th>Date</th>
      <th>Time</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Region</th>
      <th>Animal</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sightings.each do |sighting| %>
      <tr>
        <td><%= sighting.date %></td>
        <td><%= sighting.time %></td>
        <td><%= sighting.latitude %></td>
        <td><%= sighting.longitude %></td>
        <td><%= sighting.region %></td>
        <td><a href='animals/<%=sighting.animal_id%>'><%= sighting.animal.common_name %></a></td>
        <td><%= link_to 'Show', sighting %></td>
        <td><%= link_to 'Edit', edit_sighting_path(sighting) %></td>
        <td><%= link_to 'Destroy', sighting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<form action="/sightings" method="get">
  <label class ="tacos" for="start_date">Start date</label>
  <input id="start_date" name="start_date" type="text">
  <label class ="tacos" for="end_date">End date</label>
  <input id="end_date" name="end_date" type="text">
  <div class="field">
  <%= select_tag("region", options_for_select([['north' ,'north'], ['south', 'south'], ['east', 'east'], ['west', 'west']])) %>
  </div>
  <button>Run report</button>
</form>

<br>
<div id="calendar"></div>


<br>

<%= link_to 'New Sighting', new_sighting_path %>

app/views/sightings/new.html.erb
<h1>New Sighting</h1>

<%= render 'form' %>

<%= link_to 'Back', sightings_path %>

app/views/sightings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @sighting.date %>
</p>

<p>
  <strong>Time:</strong>
  <%= @sighting.time %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @sighting.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @sighting.longitude %>
</p>

<p>
  <strong>Region:</strong>
  <%= @sighting.region %>
</p>

<p>
  <strong>Animal:</strong>
  <%= @sighting.animal.common_name %>
</p>

<%= link_to 'Edit', edit_sighting_path(@sighting) %> |
<%= link_to 'Back', sightings_path %>